<link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
<style>
.ui-autocomplete { z-index:2147483647; }
</style>
<div class="wo_settings_page wow_content">
	<div class="avatar-holder">
		<img src="<?php echo $wo['setting']['avatar']?>" alt="<?php echo $wo['setting']['name']?> Profile Picture" class="avatar">
		<div class="infoz">
			<h5 title="<?php echo $wo['setting']['name']?>"><a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['setting']['username'] . '');?>" data-ajax="?link1=timeline&u=<?php echo $wo['setting']['username'] ?>"><?php echo $wo['setting']['name']?></a></h5>
			<p><?php echo $wo['lang']['profile_setting']; ?></p>
		</div>
	</div>
	<hr>

	<form  method="post" class="form-horizontal setting-profile-form">
		<div class="setting-profile-alert setting-update-alert"></div>
		
		<div class="row">
			<div class="col-md-6">
				<div class="wow_form_fields">
					<label for="first_name"><?php echo $wo['lang']['first_name']; ?></label>  
					<input id="first_name" name="first_name" type="text" value="<?php echo $wo['setting']['first_name'];?>">
				</div>
			</div>
			<div class="col-md-6">
				<div class="wow_form_fields">
					<label for="last_name"><?php echo $wo['lang']['last_name']; ?></label>  
					<input id="last_name" name="last_name" type="text" value="<?php echo $wo['setting']['last_name'];?>">
				</div>
			</div>
		</div>
		<div class="wow_form_fields">
			<label for="about"><?php echo $wo['lang']['about_me']; ?></label>  
			<?php $text = br2nl($wo['setting']['about']); ?>
			<textarea id="about" name="about" rows="4"><?php echo $text;?></textarea>
		</div>
		<div class="wow_form_fields">
			<label for="address"><?php echo $wo['lang']['location']; ?></label>  
			<input id="address" name="address" type="text" value="<?php echo $wo['setting']['address'];?>">
		</div>
		<!-- <div class="wow_form_fields mb-0">
			<label for="school"><?php echo $wo['lang']['school']; ?></label>  
		</div>
		<div class="row">
			<div class="col-md-6">
				<div class="wow_form_fields mt-0">
					<input id="school" name="school" type="text" value="<?php echo $wo['setting']['school'];?>">
				</div>
			</div>
			<div class="col-md-6 round-check">
				<input type="checkbox" id="completed" name="completed" <?php echo ($wo['setting']['school_completed'] == 1)   ? 'checked' : '';?>>
				<label for="completed"><?php echo $wo['lang']['completed']; ?></label>
			</div>
		</div>
		<hr> -->
		<div class="wow_form_fields mb-0">
			<label for="working"><?php echo $wo['lang']['working_at']; ?></label>  
		</div>
		<div class="row">
			<div class="col-md-6">
				<div class="wow_form_fields mt-0">
					<input id="working" name="working" type="text" value="<?php echo $wo['setting']['working'];?>">
					<span class="help-block">(e.g Apple)</span>
				</div>
			</div>
			<div class="col-md-6">
				<div class="wow_form_fields mt-0">
					<input id="working_link" name="working_link" type="text" value="<?php echo $wo['setting']['working_link'];?>">
					<span class="help-block"><?php echo $wo['lang']['company_website']; ?></span>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<div class="wow_form_fields">
					<label for="website"><?php echo $wo['lang']['website']; ?></label>
					<input id="website" name="website" type="text" value="<?php echo $wo['setting']['website'];?>">
				</div>
			</div>
			<div class="col-md-6">
				<div class="wow_form_fields">
					<label for="relationship"><?php echo $wo['lang']['relationship']; ?></label>
					<select id="relationship" name="relationship" onchange="if(this.value > 1 && this.value <= 4){$('#choose_rel_ship').modal('show');}">
						<option value="0"><?php echo $wo['lang']['none']; ?></option>
						<?php 
							foreach ($wo['relationship'] as $relationship_ids => $relationship) { 
							$relationship_id = $wo['setting']['relationship_id'];
							$selected_relationship = ($relationship_ids == $relationship_id) ? ' selected' : '' ;
						?>
							<option value="<?php echo $relationship_ids;?>" <?php echo $selected_relationship;?> ><?php echo $relationship;?></option>
						<?php } ?>
					</select>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<button type="button" class="btn btn-main" onclick="$('#school_list').modal('show')"><?php echo Wo_Lang($wo['lang'],'add_school'); ?></button>
				<button type="button" class="btn btn-primary" onclick="$('#work_list').modal('show')"><?php echo Wo_Lang($wo['lang'],'add_occupation') ?></button>
			</div>
		</div>

		<?php
			$fields = Wo_GetProfileFields('profile');
			if (count($fields) > 0) {
				foreach ($fields as $key => $wo['field']) {
					echo Wo_LoadPage('setting/profile-fields');
				}
				echo '<input name="custom_fields" type="hidden" value="1">';
			}
		?>
		
		<div class="text-center">
			<button type="submit" class="btn btn-main btn-mat btn-mat-raised add_wow_loader"><?php echo $wo['lang']['save']; ?></button>
		</div>

		<input type="hidden" name="user_id" id="user-id" value="<?php echo $wo['setting']['user_id'];?>">
		<input type="hidden" name="relationship_user" id="relationship_user_id" value="0">
		<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
	</form>
</div>

<div class="modal fade" id="choose_rel_ship" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="$('#relationship_user_id').val(0);"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['relationship_status']; ?></h4>
			</div>
			<div class="choose_rel_ship_alert">
             
			</div>
			<div class="modal-body">
				<div class="col-md-3">
					<div class="choose_rel_ship_avatar">
						<div>
							<i class="fa fa-user-circle-o"></i>
						</div>
					</div>
				</div>
				<div class="col-md-9">
					<div class="form-group">
						<input type="text" class="form-control" onkeyup="Wo_RelationshipSearch(this.value);" placeholder="<?php echo $wo['lang']['username']; ?>">
						<div>
							<div class="dropdown" id="select_relationship_with">
								<ul class="dropdown-menu" style="width: 100%;">
                        
								</ul>
							</div>
						</div>
					</div>
					<div class="form-group choose_rel_ship_meta" >
						<h4></h4>
						<p class="user-lastseen"></p>  
					</div>
				</div>
				<div class="clear"></div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-main" data-dismiss="modal"><?php echo $wo['lang']['save']; ?></button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="school_list" role="dialog" x-data="schoolData" @load-school-list.window="getListSchool">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['school_list']; ?></h4>
			</div>
			<div class="choose_rel_ship_alert">
             
			</div>
			<div class="modal-body">
				<button type="button" class="btn btn-info" @click="addSchool()"><?php echo $wo['lang']['add']; ?></button>
				<hr>
				<table class="table table-bordered">
					<tr>
						<th>#</th>
						<th><?php echo Wo_Lang($wo['lang'],'school_grade'); ?></th>
						<th><?php echo Wo_Lang($wo['lang'],'school_name'); ?></th>
						<th><?php echo Wo_Lang($wo['lang'],'field_of_study'); ?></th>
						<th><?php echo Wo_Lang($wo['lang'],'school_completed'); ?></th>
						<th><?php echo Wo_Lang($wo['lang'],'from_year'); ?></th>
						<th><?php echo Wo_Lang($wo['lang'],'to_year'); ?></th>
						<th><?php echo Wo_Lang($wo['lang'],'school_attachment'); ?></th>
						<th></th>
					</tr>
					<template x-for="(sch,index) in listSchool" :key="sch.school_name">
					<tr>
						<td x-text="index+1"></td>
						<td x-text="sch.school_grade"></td>
						<td x-text="sch.school_name"></td>
						<td x-text="sch.field_of_study"></td>
						<td x-text="sch.school_completed"></td>
						<td x-text="sch.from_year"></td>
						<td x-text="sch.to_year"></td>
						<td><a :href="'<?php echo $wo['config']['site_url']; ?>/'+sch.school_attachment" target="_blank"><?= $wo['lang']['school_attachment']; ?></a></td>
						<td><button class="btn btn-primary btn-sm" @click="editRow(index)">Edit</button>
							<button class="btn btn-danger btn-sm" @click="deleteRow(sch.id)">Del</button>
						</td>
					</tr>
					</template>
				</table>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-main" data-dismiss="modal"><?php echo $wo['lang']['close']; ?></button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="work_list" role="dialog" x-data="workData" @load-work-list.window="getListWork">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo Wo_Lang($wo['lang'],'company_list'); ?></h4>
			</div>
			<div class="choose_rel_ship_alert">
             
			</div>
			<div class="modal-body">
				<button type="button" class="btn btn-info" @click="addWork()"><?php echo $wo['lang']['add']; ?></button>
				<hr>
				<table class="table table-bordered">
					<tr>
						<th>#</th>
						<th><?php echo Wo_Lang($wo['lang'],'company_name'); ?></th>
						<th><?php echo Wo_Lang($wo['lang'],'company_position'); ?></th>
						<th><?php echo Wo_Lang($wo['lang'],'company_city'); ?></th>
						<th><?php echo Wo_Lang($wo['lang'],'job_description'); ?></th>
						<th><?php echo Wo_Lang($wo['lang'],'still_work'); ?></th>
						<th><?php echo Wo_Lang($wo['lang'],'from_year'); ?></th>
						<th><?php echo Wo_Lang(['lang'],'to_year'); ?></th>
						<th></th>
					</tr>
					<template x-for="(cmp,index) in listCompany" :key="cmp.company_name">
					<tr>
						<td x-text="index+1"></td>
						<td x-text="cmp.company_name"></td>
						<td x-text="cmp.company_position"></td>
						<td x-text="cmp.company_city"></td>
						<td x-text="cmp.job_description"></td>
						<td x-text="cmp.still_work"></td>
						<td x-text="cmp.from_month+' - '+cmp.from_year"></td>
						<td x-text="cmp.to_month+' - '+cmp.to_year"></td>
						<td><button class="btn btn-primary btn-sm" @click="editRow(index)">Edit</button>
							<button class="btn btn-danger btn-sm" @click="deleteRow(cmp.id)">Del</button>
						</td>
					</tr>
					</template>
				</table>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-main" data-dismiss="modal"><?php echo $wo['lang']['close']; ?></button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="school_form" role="dialog" x-data="schoolForm" @set-row.window="setRow($event.detail)">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['school_form']; ?></h4>
			</div>
			<div class="choose_rel_ship_alert">
             
			</div>
			<div class="modal-body">
				<form>
					<div class="wow_form_fields">
						<label for="school_grade"><?php echo $wo['lang']['school_grade']; ?></label>  
						<select id="school_grade" name="school_grade" x-model="form.school_grade">
							<option value="">-<?php echo $wo['lang']['school_grade']; ?>-</option>\
							<option>SMA</option>
							<option>D1</option>
							<option>D3</option>
							<option>D4</option>
							<option>S1</option>
							<option>S2</option>
							<option>S3</option>
						</select>
					</div>
					<div class="wow_form_fields">
						<label for="school_name"><?php echo $wo['lang']['school_name']; ?></label>  
						<input x-model="form.school_name" id="school_name" name="school_name" type="text" placeholder="<?php echo  $wo['lang']['school_name']; ?>">
					</div>
					<div class="wow_form_fields">
						<label for="field_of_study"><?php echo $wo['lang']['field_of_study']; ?></label>  
						<input x-model="form.field_of_study" id="field_of_study" name="field_of_study" type="text" placeholder="<?php echo  $wo['lang']['field_of_study']; ?>">
					</div>
					<div class="row">
						<div class="col-md-6 round-check">
							<input type="checkbox" id="completed" name="school_completed" x-model="form.school_completed" value="1">
							<label for="completed"><?php echo $wo['lang']['school_completed']; ?></label>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<div class="wow_form_fields">
								<label for="from_year"><?php echo $wo['lang']['from_year']; ?></label>  
								<input x-model="form.from_year" id="from_year" name="from_year" type="number">
							</div>
						</div>
						<div class="col-md-6">
							<div class="wow_form_fields">
								<label for="to_year"><?php echo $wo['lang']['to_year']; ?></label>  
								<input x-model="form.to_year" id="to_year" name="to_year" type="number">
							</div>
						</div>
					</div>
					<div class="wow_form_fields">
						<label for="school_attachment"><?php echo $wo['lang']['school_attachment']; ?></label>  
						<input type="file" id="school_attachment">
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-main" @click="doSave"><?php echo $wo['lang']['save']; ?></button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="work_form" role="dialog" x-data="workForm" @set-row-work.window="setRow($event.detail)">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['school_form']; ?></h4>
			</div>
			<div class="choose_rel_ship_alert">
             
			</div>
			<div class="modal-body">
				<form>
					<div class="wow_form_fields">
						<label for="company_name"><?php echo Wo_Lang($wo['lang'],'company_name'); ?></label>  
						<input x-model="form.company_name" id="company_name" name="company_name" type="text" placeholder="<?php echo Wo_Lang($wo['lang'],'company_name'); ?>">
					</div>
					<div class="wow_form_fields">
						<label for="company_position"><?php echo Wo_Lang($wo['lang'],'company_position'); ?></label>  
						<input x-model="form.company_position" id="company_position" name="company_position" type="text" placeholder="<?php echo Wo_Lang($wo['lang'],'company_position'); ?>">
					</div>
					<div class="wow_form_fields">
						<label for="company_city"><?php echo Wo_Lang($wo['lang'],'company_city'); ?></label>  
						<input x-model="form.company_city" id="company_city" name="company_city" type="text" placeholder="<?php echo Wo_Lang($wo['lang'],'company_city'); ?>">
					</div>
					<div class="wow_form_fields">
						<label for="job_description"><?php echo Wo_Lang($wo['lang'],'job_description'); ?></label>  
						<textarea x-model="form.job_description" id="job_description" name="job_description" placeholder="<?php echo Wo_Lang($wo['lang'],'job_description'); ?>"></textarea>
					</div>
					<div class="row">
						<div class="col-md-6 round-check">
							<input type="checkbox" id="still_work" name="still_work" x-model="form.still_work" value="1">
							<label for="still_work"><?php echo Wo_Lang($wo['lang'],'still_work'); ?></label>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<div class="wow_form_fields">
								<label for="from_month"><?php echo Wo_Lang($wo['lang'],'from_month'); ?></label>  
								<select x-model="form.from_month">
									<?php foreach(range(1,12) as $month) : ?>
									<option><?php echo sprintf('%02s',$month); ?></option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						<div class="col-md-3">
							<div class="wow_form_fields">
								<label for="from_year"><?php echo $wo['lang']['from_year']; ?></label>  
								<input x-model="form.from_year" id="from_year" name="from_year" type="number">
							</div>
						</div>
						<div class="col-md-3">
							<div class="wow_form_fields">
								<label for="to_month"><?php echo Wo_Lang($wo['lang'],'to_month'); ?></label>  
								<select x-model="form.to_month">
									<?php foreach(range(1,12) as $month) : ?>
									<option><?php echo sprintf('%02s',$month); ?></option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						<div class="col-md-3">
							<div class="wow_form_fields">
								<label for="to_year"><?php echo Wo_Lang($wo['lang'],'to_year'); ?></label>  
								<input x-model="form.to_year" id="to_year" name="to_year" type="number">
							</div>
						</div>
					</div>
					
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-main" @click="doSave"><?php echo $wo['lang']['save']; ?></button>
			</div>
		</div>
	</div>
</div>
<script defer src="https://unpkg.com/alpinejs@3.5.1/dist/cdn.min.js"></script>
<script type="text/javascript">
var relationship_users = [];
var relationship_user  = 0;
function Wo_RelationshipSearch(name = ''){
  if (!name) { return false;}
  $.ajax({
    url: Wo_Ajax_Requests_File(),
    type: 'GET',
    dataType: 'json',
    data: {f: 'family',s:'search',name:name},
  })
  .done(function(data) {
    if (data.status == 200 && data.users.length > 0) {
      relationship_users = data.users
      var html = '';
      for (var i = 0; i < data.users.length; i++) {
        html += '<li class="pointer select_relationship_user" data-id="'+i+'"><a>'+data.users[i].name+'</a></li>';        
      }
      $("#select_relationship_with").addClass('open').find('ul').html(html);
    }
    else{
      $("#select_relationship_with").removeClass('open');
    }
  })
  .fail(function() {
    console.log("error");
  })
}

$(function() {
  $(document).on('click', '.select_relationship_user', function(event) {
    event.preventDefault();
    var user_data     = relationship_users[$(this).attr('data-id')];
    $("#relationship_user_id").val(user_data.user_id);
    $(".choose_rel_ship_meta").find('h4').text(user_data.name);
    $(".choose_rel_ship_meta").find('p').html(user_data.lastseen);
    $(".choose_rel_ship_avatar").html('<img src="'+user_data.avatar+'" alt="Picture">');
    $("#select_relationship_with").removeClass('open').find('ul').empty();
  });

  $('form.setting-profile-form').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_profile_setting',
    beforeSend: function() {
      $('.wo_settings_page').find('.add_wow_loader').addClass('btn-loading');
    },
    success: function(data) {
      if (data.status == 200) {
        <?php if($wo['user']['user_id'] == $wo['setting']['user_id']) { ?>
        if (data.first_name != '' || data.last_name != '') {
        	<?php if ($wo['config']['node_socket_flow'] == "1") { ?>
            socket.emit("on_name_changed", {from_id: _getCookie("user_id"), name: data.first_name + ' ' + data.last_name});
            <?php } ?>
          $('[id^=user-full-name]').text(data.first_name + ' ' + data.last_name);
        }
        <?php } ?>
        scrollToTop();
        $('.setting-profile-alert').html('<div class="alert alert-success">' + data.message + '</div>');
        $('.alert-success').fadeIn('fast', function() {
          $(this).delay(2500).slideUp(500, function() {
            $(this).remove();
          });
        });
      } else if (data.errors) {
        var errors = data.errors.join("<br>");
        scrollToTop();
        $('.setting-profile-alert').html('<div class="alert alert-danger">' + errors + '</div>');
        $('.alert-danger').fadeIn(300);
      }
      $('.wo_settings_page').find('.add_wow_loader').removeClass('btn-loading');
    }
  });
});
  var pac_input = document.getElementById('address');
  (function pacSelectFirst(input) {
    // store the original event binding function
    var _addEventListener = (input.addEventListener) ? input.addEventListener : input.attachEvent;
    function addEventListenerWrapper(type, listener) {
      // Simulate a 'down arrow' keypress on hitting 'return' when no pac suggestion is selected,
      // and then trigger the original listener.
      if(type == "keydown") {
        var orig_listener = listener;
        listener = function (event) {
          var suggestion_selected = $(".pac-item-selected").length > 0;
          if(event.which == 13 && !suggestion_selected) {
            var simulated_downarrow = $.Event("keydown", {
              keyCode: 40,
              which: 40
            });
            orig_listener.apply(input, [simulated_downarrow]);
          }
          orig_listener.apply(input, [event]);
        };
      }
      // add the modified listener
      _addEventListener.apply(input, [type, listener]);
    }
    if(input.addEventListener)
      input.addEventListener = addEventListenerWrapper;
    else if(input.attachEvent)
      input.attachEvent = addEventListenerWrapper;
  })(pac_input);

  <?php if ($wo['config']['google_map']) { ?>
  $(function () {
     var autocomplete = new google.maps.places.Autocomplete(pac_input);
  });
  <?php }?>
</script>

<script>
 document.addEventListener('alpine:init',() => {
	 Alpine.data("schoolData",() => ({
		listSchool:[],
		init() {
			this.getListSchool()
		},
		getListSchool() {
			$.post(Wo_Ajax_Requests_File()+"?f=get_school_data",{user_id:<?php echo $wo['setting']['user_id'];?>}).done(resp => {
				this.listSchool = resp;
				
			})
		},
		addSchool() {
			let form = {
				user_id:<?php echo $wo['setting']['user_id'];?>,
				school_grade:"",
				school_name:"",
				school_completed:0,
				field_of_study:"",
				from_year:"",
				to_year:"",
				id:0
			};
			this.$dispatch('set-row',form);
			$('#school_form').modal('show');
		},
		editRow(index) {
			//alert(index);
			$('#school_form').modal('show');
			this.$dispatch('set-row',this.listSchool[index]);
		},
		deleteRow(id) {
			if (confirm(" Are you sure you want to delete this School?")) {
				$.post(Wo_Ajax_Requests_File()+'?f=delete_school',{id:id}).done(resp => {
					if (resp.error == false) {
						this.getListSchool()
					} else {
						alert("Error Delete School");
					}
				})
			}
		}
	 }));
	 
	 Alpine.data("schoolForm",() => ({
		form:{
			user_id:<?php echo $wo['setting']['user_id'];?>,
			school_grade:"",
			school_name:"",
			school_completed:0,
			field_of_study:"",
			from_year:"",
			to_year:"",
			id:0
		},
		init() {
			var that = this;
			$( "#school_name" ).autocomplete({
			  source: function( request, response ) {
				$.ajax( {
				  url: Wo_Ajax_Requests_File() + '?f=get_school_list',
				  dataType: "json",
				  data: {
					term: request.term
				  },
				  success: function( data ) {
					response( data );
				  }
				} );
			  },
			  minLength: 2,
			  select: function( event, ui ) {
				//log( "Selected: " + ui.item.value + " aka " + ui.item.id );
				that.form.school_name = ui.item.label;
			  }
			} );
		},
		doSave() {
			var file_data = $('#school_attachment').prop('files')[0]; 
			var formData = new FormData();
			formData.append('file',file_data);
			for (form in this.form) {
				formData.append(form,this.form[form]);
			}
			
			 $.ajax({
				url: Wo_Ajax_Requests_File()+'?f=upsert_school',
				type: 'post',
				data: formData,
				contentType: false,
				processData: false,
				success: response => {
					if (response.error == false) {
						$('#school_form').modal('hide');
						this.$dispatch('load-school-list');
						$('.setting-profile-alert').html('<div class="alert alert-success">' + data.message + '</div>');
						$('.alert-success').fadeIn('fast', function() {
						  $(this).delay(2500).slideUp(500, function() {
							$(this).remove();
						  });
						});
					}
				},
           });
		},
		setRow(row) {
			this.form = row;
		}
	  }))
	  
	  Alpine.data("workData",() => ({
		listCompany:[],
		init() {
			this.getListWork()
		},
		getListWork() {
			$.post(Wo_Ajax_Requests_File()+"?f=get_occupation_data",{user_id:<?php echo $wo['setting']['user_id'];?>}).done(resp => {
				this.listCompany = resp;
				
			})
		},
		addWork() {
			let form = {
				user_id:<?php echo $wo['setting']['user_id'];?>,
				company_name:"",
				company_position:"",
				company_city:"",
				job_description:"",
				still_work:0,
				from_year:"",
				from_month:"01",
				to_year:"",
				to_month:"01",
				id:0
			};
			this.$dispatch('set-row-work',form);
			$('#work_form').modal('show');
		},
		editRow(index) {
			//alert(index);
			$('#work_form').modal('show');
			this.$dispatch('set-row-work',this.listCompany[index]);
		},
		deleteRow(id) {
			if (confirm(" Are you sure you want to delete this Occupation?")) {
				$.post(Wo_Ajax_Requests_File()+'?f=delete_occupation',{id:id}).done(resp => {
					if (resp.error == false) {
						this.getListWork()
					} else {
						alert("Error Delete Occupation");
					}
				})
			}
		}
	 }));
	  
	 Alpine.data("workForm",() => ({
		form:{
			user_id:<?php echo $wo['setting']['user_id'];?>,
			company_name:"",
			company_position:"",
			company_city:"",
			job_description:"",
			still_work:0,
			from_year:"",
			from_month:"01",
			to_year:"",
			to_month:"01",
			id:0
		},
		init() {
		},
		doSave() {
			$.post(Wo_Ajax_Requests_File()+'?f=upsert_occupation',this.form).done(response => {
				if (response.error == false) {
						$('#work_form').modal('hide');
						this.$dispatch('load-school-list');
						$('.setting-profile-alert').html('<div class="alert alert-success">' + data.message + '</div>');
						$('.alert-success').fadeIn('fast', function() {
						  $(this).delay(2500).slideUp(500, function() {
							$(this).remove();
						  });
						});
					}
			})
		},
		setRow(row) {
			this.form = row;
		}
	  }))
 });
</script>